# data-dir contains protobuf files. It's suggested to use fullpath.
data-dir = "./data.drainer"

# log-file = ""
# log-rotate = "hour"
log-level = "info"

# start-datetime and stop-datetime enable you to pick a range of binlog to recovery.
# The datetime format is like '2018-02-28 12:12:12'. 
# start-datetime = ""
# stop-datetime = ""

# Start-tso is similar to start-datetime, but in pd-server tso format. e.g.  395181938313123110
# Stop-tso is similar to stop-datetime, but in pd-server tso format. e.g. 395181938313123110
# start-tso = 0 
# stop-tso = 0

# dest-type choose a destination, which value can be "mysql", "print". 
# for print, it just prints decoded value.
dest-type = "print"

##replicate-do-db priority over replicate-do-table if have same db name
##and we support regular expression , start with '~' declare use regular expression.
#
replicate-do-db = ["sbtest3","sbtest4"]
#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "log"

#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "~^a.*"

replicate-ignore-db = ["sbtest3", "sbtest4"]
#[[replicate-ignore-table]]
#db-name ="sbtest4"
#tbl-name = "~^sbtest[2-5]"
#
[dest-db]
host = "127.0.0.1"
port = 4000
user = "root"
password = ""
