{
 "title": "Binlog",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "drainer_instance",
    "query": "label_values(binlog_drainer_ddl_jobs_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "TSO - pipline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tips ",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "content": "\n# TSO\n\n1. PUMP GC TSO < PUMP max commit TSO \n2. PUMP GC TSO < Drainer Pull PUMP handle TSO\n3. PUMP GC TSO < Draienr checkpoint TSO\n\n## alert\n\n1. drainer checkpoint tso no change for 1m\n2. drainer checkpoint tso delay > 1 hour\n3. PUMP disk space <= 10G\n\n\n### read more: https://docs.pingcap.com/zh/tidb/stable/tidb-binlog-overview\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Binlog alert",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Binlog File GC TSO --- Metadata",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    { "expr": "binlog_pump_storage_gc_ts", "legendFormat": "{{instance}} : gc_tso" }
   ]
  },
  {
   "title": "New Binlog File  TSO -- Metadata",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "binlog_pump_storage_max_commit_ts",
     "legendFormat": "{{instance}} : max_commit_tso"
    }
   ]
  },
  {
   "title": "Drainer Pull Pump Handle TSO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "binlog_drainer_pump_position{instance = \"$drainer_instance\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Drainer checkpoint TSO",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "binlog_drainer_checkpoint_tso", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Drainer checkpoit  no cheange for 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(binlog_drainer_checkpoint_tso[1m]) ",
     "legendFormat": "{{instance}}  change[1m]"
    }
   ]
  },
  {
   "title": "Drainer checkpoint delay > 1 hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() - binlog_drainer_checkpoint_tso / 1000)",
     "legendFormat": "{{instance}} delay time"
    }
   ]
  },
  {
   "title": "pump",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "capacity -- Storage Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_storage_size_bytes{type=\"capacity\"}",
       "legendFormat": "{{instance}} : {{type}}"
      }
     ]
    },
    {
     "title": "available -- Storage Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_storage_size_bytes{type=\"available\"}",
       "legendFormat": "{{instance}} : {{type}}"
      }
     ]
    },
    {
     "title": "Binlog File GC TSO --- Metadata",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      { "expr": "binlog_pump_storage_gc_ts", "legendFormat": "{{instance}} : gc_tso" }
     ]
    },
    {
     "title": "New Binlog File  TSO -- Metadata",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_max_commit_ts",
       "legendFormat": "{{instance}} : max_commit_tso"
      }
     ]
    },
    {
     "title": "Write Binlog QPS by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(binlog_pump_rpc_duration_seconds_count{method=\"WriteBinlog\"}[1m])",
       "legendFormat": "{{instance}} :: {{label}}"
      }
     ]
    },
    {
     "title": "Write Binlog Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_rpc_duration_seconds_bucket{method=\"WriteBinlog\"}[1m]))",
       "legendFormat": "{{instance}} : {{method}}:99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_rpc_duration_seconds_bucket{method=\"WriteBinlog\"}[1m]))",
       "legendFormat": "{{instance}} : {{method}} : 95"
      }
     ]
    },
    {
     "title": "Storage Write Binlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_storage_write_binlog_size_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}} : 99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_storage_write_binlog_size_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}} : 95"
      }
     ]
    },
    {
     "title": "Storage Write Binlog Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_storage_write_binlog_duration_time_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}}:99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_storage_write_binlog_duration_time_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}}:95"
      }
     ]
    },
    {
     "title": "Pump Storage Error By Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(binlog_pump_storage_error_count[1m])",
       "legendFormat": "{{instance}}:{{type}}"
      }
     ]
    },
    {
     "title": "Query Tikv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_query_tikv_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TiDB Server Skip Binlog Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_server_critical_error_total",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "drainer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoint TSO",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "binlog_drainer_checkpoint_tso{instance = \"$drainer_instance\"}",
       "legendFormat": "checkpoint tso"
      }
     ]
    },
    {
     "title": "Pump Handle TSO",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_pump_position{instance = \"$drainer_instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Pull Binlog QPS by  Pump NodeID",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(binlog_drainer_read_binlog_size_count{instance = \"$drainer_instance\"}[1m])) by (nodeID)",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "95% Binlog Reach Duration By Pump",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(binlog_drainer_binlog_reach_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Error By Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_error_count{instance = \"$drainer_instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Drainer Event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(binlog_drainer_event{instance = \"$drainer_instance\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% Execute Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_drainer_execute_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "99% sql query Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_drainer_query_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "95% Binlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(binlog_drainer_read_binlog_size_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "pump: {{nodeID}}"
      }
     ]
    },
    {
     "title": "DDL Job Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_ddl_jobs_total{instance = \"$drainer_instance\"}",
       "legendFormat": "ddl job count"
      }
     ]
    },
    {
     "title": "queue size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_queue_size{instance = \"$drainer_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutine",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=~\"binlog|pump|drainer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"binlog|pump|drainer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}