# cistern Configuration.

# addr (i.e. 'host:port') to listen on for drainer connections
addr = "127.0.0.1:8249"

# the interval time (in seconds) of detect pumps' status
detect-interval = 10

# path to the data directory of kv store
data-dir = "data.cistern"

# an integer value to control expiry date of the binlog data, indicates for how long (in days) the binlog data would be stored
# (default value is 0, means binlog data would never be removed)
gc = 0

# a comma separated list of PD endpoints
pd-urls = "http://127.0.0.1:2379"
