# drainer Configuration.

log-level = "info"

data-dir = "data.drainer"
txn-batch = 1
request-count=1000

pprof-addr = ":10081"

pd-path = "127.0.0.1:2379?cluster=1"

[client]
host = "127.0.0.1"
port = 8249

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 3306
