# drainer Configuration.

log-level = "info"

id = 101

meta = "syncer.meta"
init-ts = 0
batch = 1
request-bacth=1

pprof-addr = ":10081"

store-path = "tikv://127.0.0.1:2379?cluster=1"

[client]
host = "127.0.0.1"
port = "10000"

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 3306
